services:
  python-app:
    image: python:3.12-slim
    # container_name: ...
    working_dir: /app
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    environment:
      - PIP_CACHE_DIR=/root/.cache/pip
    command: ["tail", "-f", "/dev/null"]
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "6.0"
    #       memory: 12G

volumes:
  pip_cache:
    driver: local
